# Site settings
title: Clean N Clean
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
#baseurl: "/"
url: ""
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num"
#destination: _site/blog

exclude: ["node_modules"]


#gems:
#- jekyll-mentions
#- jemoji
#- jekyll-redirect-from
#- jekyll-sitemap